import {
  nitendo,
  shirtmern,
  shopbook,
  instagram,
  basketballprofile,
  socialmui,
  mernlearn,
  movieapi,
  shoesstore,
  netflix,
  linefriends,
  wavelane,
  agency,
  burro,
  cakeshop,
  tesla,
  disney,
  youtubeclone,
  basketball,
  imagedesign,
  boomclub,
  coffehouse,
  portfoliotemplate,
  tinder,
  todolist,
  quiz,
  mercedes,
  tixcinema,
  cinemadtv,
  homestead,
  housing,
  clothes,
} from '../assets/images';
export const projects = [
  {
    id: 1,
    title: 'NITENDO',
    category: 'ReactJS, Tailwindcss',
    linkImg: nitendo,
    linkDemo: 'https://nitendo-clone.netlify.app',
  },
  {
    id: 2,
    title: 'Shop T-shirt',
    category: 'ReactJS, NodeJS, Mongoose',
    linkImg: shirtmern,
    linkDemo: 'https://tshirtdev.netlify.app',
  },
  {
    id: 3,
    title: 'Shop Book',
    category: 'ReactJS, Firebase',
    linkImg: shopbook,
    linkDemo: 'https://shop-bae1a.firebaseapp.com',
  },
  {
    id: 4,
    title: 'Clone Instagram',
    category: 'ReactJS, Firebase, SASS',
    linkImg: instagram,
    linkDemo: 'https://hosting-instagram-clone.firebaseapp.com',
  },
  {
    id: 5,
    title: 'Basketball Profile',
    category: 'ReactJS, Tailwindcss, Framer-motion',
    linkImg: basketballprofile,
    linkDemo: 'https://basketball-profile.web.app',
  },
  {
    id: 6,
    title: 'Social Mui',
    category: 'ReactJS, Material UI',
    linkImg: socialmui,
    linkDemo: 'https://social-mui.netlify.app',
  },
  {
    id: 7,
    title: 'MERN LEARN',
    category: 'ReactJS, Express, Mongoose',
    linkImg: mernlearn,
    linkDemo: 'https://angry-euler-1c98ac.netlify.app',
  },
  {
    id: 8,
    title: 'MOVIE-API',
    category: 'ReactJS, API',
    linkImg: movieapi,
    linkDemo: 'https://film-api-redux-2021.firebaseapp.com',
  },
  {
    id: 9,
    title: 'Shoes Store',
    category: 'ReactJS, Firebase',
    linkImg: shoesstore,
    linkDemo: 'https://shoes-dtv.firebaseapp.com',
  },
  {
    id: 10,
    title: 'Netflix HomePage',
    category: 'ReactJS, API',
    linkImg: netflix,
    linkDemo: 'http://netflix-home.surge.sh',
  },
  {
    id: 11,
    title: 'LINE FRIENDS',
    category: 'ReactJS, Firebase',
    linkImg: linefriends,
    linkDemo: 'https://line-friends-clone.web.app',
  },
  {
    id: 12,
    title: 'WAVELANE',
    category: 'ReactJS, Firebase',
    linkImg: wavelane,
    linkDemo: 'https://clone-wave-lane.firebaseapp.com',
  },
  {
    id: 13,
    title: 'AGENCY LEGEND',
    category: 'ReactJS, Firebase',
    linkImg: agency,
    linkDemo: 'https://agency-clone.web.app',
  },
  {
    id: 14,
    title: 'Buro Harro',
    category: 'ReactJS, Firebase',
    linkImg: burro,
    linkDemo: 'https://clone-buro-harro-96139.firebaseapp.com',
  },
  {
    id: 15,
    title: 'Cake Shop',
    category: 'ReactJS',
    linkImg: cakeshop,
    linkDemo: 'http://clone-cakeshop.surge.sh',
  },
  {
    id: 16,
    title: 'Tesla',
    category: 'ReactJS, Styled-Components',
    linkImg: tesla,
    linkDemo: 'http://tesla-clone24.surge.sh',
  },
  {
    id: 17,
    title: 'Disney',
    category: 'ReactJS, Styled-Components',
    linkImg: disney,
    linkDemo: 'http://clone-disneydtv.surge.sh',
  },
  {
    id: 18,
    title: 'Youtube Clone',
    category: 'ReactJS, Material UI',
    linkImg: youtubeclone,
    linkDemo: 'https://clone-ddb15.firebaseapp.com',
  },
  {
    id: 19,
    title: 'Basketball',
    category: 'ReactJS, Firebase',
    linkImg: basketball,
    linkDemo: 'https://basketball-a3551.firebaseapp.com',
  },
  {
    id: 20,
    title: 'Image Desgin',
    category: 'ReactJS, Firebase',
    linkImg: imagedesign,
    linkDemo: 'https://clone-website-imagedesign98.web.app',
  },
  {
    id: 21,
    title: 'Boom Club',
    category: 'ReactJS, Firebase',
    linkImg: boomclub,
    linkDemo: 'https://clone-website-boom-club.firebaseapp.com',
  },
  {
    id: 22,
    title: 'The Coffee House',
    category: 'ReactJS, Firebase',
    linkImg: coffehouse,
    linkDemo: 'https://clone-the-coffee-house.firebaseapp.com',
  },
  {
    id: 23,
    title: 'Portfolio Template',
    category: 'ReactJS, Styled Components',
    linkImg: portfoliotemplate,
    linkDemo: 'http://portfolio-template-dtv.surge.sh',
  },
  {
    id: 24,
    title: 'Tinder',
    category: 'ReactJS, Firebase, Material UI',
    linkImg: tinder,
    linkDemo: 'https://tinder-app-a1cc2.firebaseapp.com',
  },
  {
    id: 25,
    title: 'Todo List',
    category: 'ReactJS, Material UI, AOS animation',
    linkImg: todolist,
    linkDemo: 'https://todo-dtv.firebaseapp.com',
  },
  {
    id: 26,
    title: 'Quiz',
    category: 'ReactJS, SASS',
    linkImg: quiz,
    linkDemo: 'http://quiz-dtv.surge.sh',
  },
  {
    id: 27,
    title: 'SASS Mercedes',
    category: 'HTML5, CSS3, Javascript',
    linkImg: mercedes,
    linkDemo: 'http://sass-mercedes.surge.sh',
  },
  {
    id: 28,
    title: 'Tix Cinema',
    category: 'ReactJS, Material UI',
    linkImg: tixcinema,
    linkDemo: 'http://tix-dtv.surge.sh',
  },
  {
    id: 29,
    title: 'Cinema',
    category: 'ReactJS, Material UI',
    linkImg: cinemadtv,
    linkDemo: 'https://cinema-dtv.firebaseapp.com',
  },
  {
    id: 30,
    title: 'Home Stead',
    category: 'HTML5, CSS3, Javascript',
    linkImg: homestead,
    linkDemo: 'http://home-stead.surge.sh',
  },
  {
    id: 31,
    title: 'Housing',
    category: 'HTML5, CSS3, Javascript',
    linkImg: housing,
    linkDemo: 'http://housing-dtv.surge.sh',
  },
  {
    id: 32,
    title: 'Clothes',
    category: 'HTML5, CSS3, Javascript',
    linkImg: clothes,
    linkDemo: 'http://clothes-dtv.surge.sh',
  },
];
